# absolute path to the project folder
project-folder: /proj/project_2000968/FAANG_lncRNA

# species name
species: ovis_aries

# absolute path to sample sheet (list of sample identifiers)
samples: /proj/project_2000968/FAANG_lncRNA/ovis_aries/samples

# absolute path to list of reference files (header of tsv: species, genome, index, annot)
ref: /proj/project_2000968/FAANG_lncRNA/pipeline/species_resources.tsv

params:
  fastqc: ""
  star: ""
  feelnc: ""
  stringtie:
    # Define here the tpm threshold for the merging step
    tpm: "1"
  rsem: ""
